#!/usr/bin/env node
/* ==============================================================
 * Generate studio.html — a stripped-down page with ONLY the
 * interactive figures and their controls, no prose/abstract/
 * captions. For working directly on the animations.
 *
 * It reuses index.html's <head> and js/ script includes verbatim,
 * extracts each figure that has a WoDS init call (so static result
 * figures are skipped), and re-emits the same init calls. Run it
 * whenever you change a figure's markup or controls in index.html:
 *
 *     node tools/build-studio.js
 *
 * Output: studio.html (open it the same way as index.html; append
 * ?record=1 to record, exactly like the real page).
 *
 * Each figure has an "open standalone" link to studio.html?only=<id>,
 * which loads and runs that ONE animation (the others are removed), so
 * recording isn't slowed by 14 rAF loops competing at once. The link
 * carries over the current query (?record=1, &scale=…) automatically.
 *
 * Figures that exist ONLY in the studio (authoring tools with no place
 * on the public page) live in tools/studio-extras.html and are appended
 * after the index.html ones; their scripts are listed in EXTRA_SCRIPTS.
 * ============================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

// Scripts backing the studio-only figures, injected after index.html's.
const EXTRA_SCRIPTS = [
  'js/svg_recorder.js',
  'js/interactive_pipeline_still.js',
];

// <head> contents, verbatim (fonts, theme/style css, KaTeX — control
// hints contain $...$ that KaTeX renders).
const head = src.match(/<head>([\s\S]*?)<\/head>/i)[1];

// js/ script includes, in order (config, util, solvers, figures, capture).
// The studio-only scripts go just before capture.js, keeping it last.
const scriptTags = src.match(/<script src="js\/[^"]+"><\/script>/g) || [];
const captureAt = scriptTags.findIndex((s) => s.includes('js/capture.js'));
scriptTags.splice(
  captureAt === -1 ? scriptTags.length : captureAt,
  0,
  ...EXTRA_SCRIPTS.map((s) => `<script src="${s}"></script>`)
);
const scripts = scriptTags.join('\n  ');

function section({ fn, id, html }) {
  return `    <section class="studio-item">
      <h3 class="studio-label">#${id} · WoDS.${fn} <a class="studio-open" data-only="${id}" href="?only=${id}">open standalone ↗</a></h3>
${html.replace(/^/gm, '    ')}
    </section>`;
}

// Each interactive figure is the one named by a WoDS init call.
const initRe = /WoDS\.(\w+)\(document\.getElementById\('([^']+)'\)\);/g;
const figures = [...src.matchAll(initRe)].map((m) => ({ fn: m[1], id: m[2] }))
  .map(({ fn, id }) => {
    const figRe = new RegExp(
      '<figure\\b[^>]*\\bid="' + id + '"[^>]*>[\\s\\S]*?<\\/figure>'
    );
    const fig = src.match(figRe);
    if (!fig) console.warn(`!  no <figure id="${id}"> found — skipping ${fn}`);
    return fig && { fn, id, html: fig[0] };
  }).filter(Boolean);

// Studio-only figures: <figure id="…" data-init="…"> blocks in studio-extras.html.
const extrasSrc = fs.readFileSync(path.join(root, 'tools', 'studio-extras.html'), 'utf8');
const extraRe = /<figure\b[^>]*\bid="([^"]+)"[^>]*\bdata-init="(\w+)"[^>]*>[\s\S]*?<\/figure>/g;
const extras = [...extrasSrc.matchAll(extraRe)]
  .map((m) => ({ fn: m[2], id: m[1], html: m[0] }));

const all = [...figures, ...extras];
const sections = all.map(section);
const initLines = all.map(({ fn, id }) =>
  `      { const el = document.getElementById('${id}'); if (el) WoDS.${fn}(el); }`
).join('\n');

const out = `<!doctype html>
<html lang="en">

<head>${head}  <style>
    /* Studio overrides: figures only, no prose. */
    body.studio { max-width: 920px; margin: 0 auto; padding: 2rem 1.5rem 6rem; }
    .studio-head { font: 600 14px/1.4 var(--font-mono, monospace); color: var(--color-text-muted, #6b6b6b); margin-bottom: 2rem; }
    .studio-item { margin: 0 0 4.5rem; }
    .studio-label { font: 600 12px/1 var(--font-mono, monospace); color: #999; letter-spacing: .03em; margin: 0 0 1rem; }
    .studio-open { font-weight: 500; color: var(--color-accent, #2a5fb8); text-decoration: none; margin-left: 10px; }
    .studio-open:hover { text-decoration: underline; }
    .studio-back { color: var(--color-accent, #2a5fb8); text-decoration: none; }
    .studio-back:hover { text-decoration: underline; }
    .studio-solo .studio-open { display: none; }
    .studio-item .figure-caption { display: none !important; }
    .studio-item figure.figure { margin: 0; }
  </style>
</head>

<body class="studio">
  <div class="studio-head">WoDS animation studio — generated by tools/build-studio.js. Edit figures in index.html, then regenerate. Append ?record=1 to record; use “open standalone” to run one animation lag-free.</div>

${sections.join('\n\n')}

  ${scripts}
  <script>
    document.addEventListener('DOMContentLoaded', () => {
      const only = new URLSearchParams(location.search).get('only');
      if (only) {
        // Standalone mode: keep only the requested figure so a single
        // animation runs (no contention/lag from the other figures).
        document.body.classList.add('studio-solo');
        document.querySelectorAll('.studio-item').forEach((sec) => {
          const fig = sec.querySelector('figure');
          if (!fig || fig.id !== only) sec.remove();
        });
        // Repurpose the header as a "back to studio" link (drops ?only but
        // keeps record/scale/… so you return to the same recording setup).
        const head = document.querySelector('.studio-head');
        if (head) {
          const back = document.createElement('a');
          back.className = 'studio-back';
          back.textContent = '← back to studio';
          back.href = location.pathname;
          const bp = new URLSearchParams(location.search);
          bp.delete('only');
          back.search = bp.toString();
          head.textContent = '';
          head.appendChild(back);
        }
        document.title = 'WoDS studio — ' + only;
      }
      // Carry the current query (?record=1, &scale=…) onto each standalone
      // link, minus any existing ?only, so recording settings persist.
      const keep = new URLSearchParams(location.search);
      keep.delete('only');
      document.querySelectorAll('.studio-open').forEach((a) => {
        const p = new URLSearchParams(keep);
        p.set('only', a.dataset.only);
        a.search = p.toString();
      });
${initLines}
    });
  </script>

</body>
</html>
`;

fs.writeFileSync(path.join(root, 'studio.html'), out);
console.log(`wrote studio.html — ${figures.length} interactive figures` +
  ` + ${extras.length} studio-only`);
