#!/usr/bin/env node
/* ==============================================================
 * Generate studio.html — a stripped-down page with ONLY the
 * interactive figures and their controls, no prose/abstract/
 * captions. For working directly on the animations.
 *
 * It reuses index.html's <head> and js/ script includes verbatim,
 * extracts each figure that has a WoDS init call (so static result
 * figures are skipped), and re-emits the same init calls. Run it
 * whenever you change a figure's markup or controls in index.html:
 *
 *     node tools/build-studio.js
 *
 * Output: studio.html (open it the same way as index.html; append
 * ?record=1 to record, exactly like the real page).
 * ============================================================== */
'use strict';
const fs = require('fs');
const path = require('path');

const root = path.resolve(__dirname, '..');
const src = fs.readFileSync(path.join(root, 'index.html'), 'utf8');

// <head> contents, verbatim (fonts, theme/style css, KaTeX — control
// hints contain $...$ that KaTeX renders).
const head = src.match(/<head>([\s\S]*?)<\/head>/i)[1];

// js/ script includes, in order (config, util, solvers, figures, capture).
const scripts = (src.match(/<script src="js\/[^"]+"><\/script>/g) || []).join('\n  ');

// Each interactive figure is the one named by a WoDS init call.
const initRe = /WoDS\.(\w+)\(document\.getElementById\('([^']+)'\)\);/g;
const inits = [...src.matchAll(initRe)].map((m) => ({ fn: m[1], id: m[2] }));

const sections = inits.map(({ fn, id }) => {
  const figRe = new RegExp(
    '<figure\\b[^>]*\\bid="' + id + '"[^>]*>[\\s\\S]*?<\\/figure>'
  );
  const fig = src.match(figRe);
  if (!fig) {
    console.warn(`!  no <figure id="${id}"> found — skipping ${fn}`);
    return '';
  }
  return `    <section class="studio-item">
      <h3 class="studio-label">#${id} · WoDS.${fn}</h3>
${fig[0].replace(/^/gm, '    ')}
    </section>`;
}).filter(Boolean);

const initLines = inits.map(({ fn, id }) =>
  `      { const el = document.getElementById('${id}'); if (el) WoDS.${fn}(el); }`
).join('\n');

const out = `<!doctype html>
<html lang="en">

<head>${head}  <style>
    /* Studio overrides: figures only, no prose. */
    body.studio { max-width: 920px; margin: 0 auto; padding: 2rem 1.5rem 6rem; }
    .studio-head { font: 600 14px/1.4 var(--font-mono, monospace); color: var(--color-text-muted, #6b6b6b); margin-bottom: 2rem; }
    .studio-item { margin: 0 0 4.5rem; }
    .studio-label { font: 600 12px/1 var(--font-mono, monospace); color: #999; letter-spacing: .03em; margin: 0 0 1rem; }
    .studio-item .figure-caption { display: none !important; }
    .studio-item figure.figure { margin: 0; }
  </style>
</head>

<body class="studio">
  <div class="studio-head">WoDS animation studio — generated by tools/build-studio.js. Edit figures in index.html, then regenerate. Append ?record=1 to record.</div>

${sections.join('\n\n')}

  ${scripts}
  <script>
    document.addEventListener('DOMContentLoaded', () => {
${initLines}
    });
  </script>

</body>
</html>
`;

fs.writeFileSync(path.join(root, 'studio.html'), out);
console.log(`wrote studio.html — ${inits.length} interactive figures`);
